//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SME.Utils {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataSyncResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataSyncResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SME.Utils.DataSyncResource", typeof(DataSyncResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị cuối năm tới ngày không được phép để trống.
        /// </summary>
        internal static string CUOI_NAM_TOI_NGAY {
            get {
                return ResourceManager.GetString("CUOI_NAM_TOI_NGAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị cuối năm từ ngày không được phép để trống.
        /// </summary>
        internal static string CUOI_NAM_TU_NGAY {
            get {
                return ResourceManager.GetString("CUOI_NAM_TU_NGAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị đầu năm không được phép để trống.
        /// </summary>
        internal static string DAU_NAM {
            get {
                return ResourceManager.GetString("DAU_NAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị đầu năm tới ngày không được phép để trống.
        /// </summary>
        internal static string DAU_NAM_TOI_NGAY {
            get {
                return ResourceManager.GetString("DAU_NAM_TOI_NGAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị đầu năm từ ngày không được phép để trống.
        /// </summary>
        internal static string DAU_NAM_TU_NGAY {
            get {
                return ResourceManager.GetString("DAU_NAM_TU_NGAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị trường học không được phép để trống.
        /// </summary>
        internal static string MA_TRUONG_HOC {
            get {
                return ResourceManager.GetString("MA_TRUONG_HOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị năm học không được phép để trống.
        /// </summary>
        internal static string NAM_HOC {
            get {
                return ResourceManager.GetString("NAM_HOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị ngày cập nhật không được phép để trống.
        /// </summary>
        internal static string NGAY_CAP_NHAT {
            get {
                return ResourceManager.GetString("NGAY_CAP_NHAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị ngày yêu cầu không được phép để trống.
        /// </summary>
        internal static string NGAY_YEU_CAU {
            get {
                return ResourceManager.GetString("NGAY_YEU_CAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị người cập nhật không được phép để trống.
        /// </summary>
        internal static string NGUOI_CAP_NHAT {
            get {
                return ResourceManager.GetString("NGUOI_CAP_NHAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị người yêu cầu không được phép để trống.
        /// </summary>
        internal static string NGUOI_YEU_CAU {
            get {
                return ResourceManager.GetString("NGUOI_YEU_CAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị tới năm học không được phép để trống.
        /// </summary>
        internal static string TOI_NAM_HOC {
            get {
                return ResourceManager.GetString("TOI_NAM_HOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị tới ngày không được phép để trống.
        /// </summary>
        internal static string TOI_NGAY {
            get {
                return ResourceManager.GetString("TOI_NGAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị trạng thái không được phép để trống.
        /// </summary>
        internal static string TRANG_THAI {
            get {
                return ResourceManager.GetString("TRANG_THAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị từ năm học không được phép để trống.
        /// </summary>
        internal static string TU_NAM_HOC {
            get {
                return ResourceManager.GetString("TU_NAM_HOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị từ ngày không được phép để trống.
        /// </summary>
        internal static string TU_NGAY {
            get {
                return ResourceManager.GetString("TU_NGAY", resourceCulture);
            }
        }
    }
}
